version: "3.8"

services:
  vectorcode_chunker:
    build: .
    image: vectorcode-chunker-unique:latest
    container_name: vectorcode_chunker
    volumes:
      - .:/app
    environment:
      - CHROMA_HOST=vectorcode_chromadb
      - CHROMA_PORT=8000
    depends_on:
      - vectorcode_chromadb
    entrypoint: ["tail", "-f", "/dev/null"]
    # command: ["python", "chunker.py", "chunk-and-vectorise", "deployment/tests/testproject", "*.py", "--language", "python"]

  vectorcode_chromadb:
    image: chromadb/chroma:latest
    container_name: vectorcode_chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
    volumes:
      - vectorcode_chroma_data:/chroma/.chroma

volumes:
  vectorcode_chroma_data:
