version: "3.8"

services:
  vectorcode_chunker:
    build: .
    image: vectorcode-chunker-unique:latest
    container_name: vectorcode_chunker
    volumes:
      - .:/app
    depends_on:
      - vectorcode_chromadb
    command: [
      "python", "chunker.py", "chunk-and-vectorise",
      "deployment/tests/testproject", "*.py",
      "--language", "python",
      "--chroma-host", "vectorcode_chromadb",
      "--chroma-port", "8000"
    ]

  vectorcode_chromadb:
    image: chromadb/chroma:latest
    container_name: vectorcode_chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
    volumes:
      - vectorcode_chroma_data:/chroma/.chroma

  vectorcode_chunker_test:
    build: .
    image: vectorcode-chunker-unique:latest
    container_name: vectorcode_chunker_test
    depends_on:
      - vectorcode_chunker
      - vectorcode_chromadb
    command: ["/bin/bash", "deployment/test_chunked_file.sh"]
    environment:
      - CHROMA_HOST=vectorcode_chromadb
      - CHROMA_PORT=8000
    volumes:
      - .:/app

volumes:
  vectorcode_chroma_data:
